import type { ParseResult } from "../lib/parser/types.ts";

export function renderReport(result: ParseResult): string {
  const data = JSON.stringify(result).replaceAll("<", "\\u003c");
  const { files, imports } = result.coverage;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>CodeMap</title>
<style>
:root{color-scheme:dark;--bg:#070a10;--panel:#0d131d;--line:#253246;--text:#edf5ff;--muted:#8ea1b8;--cyan:#22d3ee}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 46% 45%,#111b2a 0,#080d15 45%,var(--bg) 78%);color:var(--text);font:13px Inter,ui-sans-serif,system-ui,sans-serif;overflow:hidden}
header{height:64px;display:flex;gap:16px;align-items:center;padding:10px 18px;border-bottom:1px solid var(--line);background:#090e16e8;backdrop-filter:blur(12px)}
.brand{font-size:17px;font-weight:750;letter-spacing:.02em}.brand span{color:var(--cyan)}input{width:min(460px,38vw);background:#080d15;border:1px solid #314158;border-radius:8px;color:white;padding:10px 12px;outline:none}input:focus{border-color:var(--cyan)}
button{background:#121c29;border:1px solid #34465e;border-radius:7px;color:#dcecff;padding:8px 11px;cursor:pointer}button:hover,button.active{border-color:var(--cyan);color:white}.summary{margin-left:auto;color:var(--muted);white-space:nowrap}
main{display:grid;grid-template-columns:minmax(0,1fr) 350px;height:calc(100vh - 64px)}.stage{position:relative;min-width:0}.hint{position:absolute;left:16px;bottom:14px;color:#71859d;font-size:11px;pointer-events:none}
svg{width:100%;height:100%;cursor:grab}svg.dragging{cursor:grabbing}.module-sector{stroke-width:1;vector-effect:non-scaling-stroke}.module-label{fill:#aebed0;font-size:11px;font-weight:650;text-anchor:middle;paint-order:stroke;stroke:#080d15;stroke-width:4px;stroke-linejoin:round}.edge{fill:none;stroke:#7a8ca3;stroke-width:1;opacity:0;vector-effect:non-scaling-stroke;pointer-events:none}.show-all .edge{opacity:.075}.edge.active{stroke:var(--cyan);stroke-width:1.8;opacity:.82}.node{cursor:pointer}.node circle{stroke:#08101a;stroke-width:1.5;vector-effect:non-scaling-stroke;transition:r .12s,opacity .12s}.node.dim{opacity:.1}.node.related circle{stroke:#b8eff8;stroke-width:2}.node.selected circle{stroke:white;stroke-width:3;filter:drop-shadow(0 0 5px #22d3ee)}.node text{display:none;fill:white;font-size:11px;font-weight:650;paint-order:stroke;stroke:#07101a;stroke-width:4px;pointer-events:none}.node:hover text,.node.selected text,.node.match text{display:block}.node.match circle{stroke:#f8fafc;stroke-width:3;filter:drop-shadow(0 0 5px #fff)}
aside{border-left:1px solid var(--line);background:#0a1019ed;padding:18px;overflow:auto}aside h2{font-size:15px;margin:0 0 9px;overflow-wrap:anywhere}aside h3{font-size:11px;text-transform:uppercase;letter-spacing:.12em;color:#8196ae;margin:22px 0 8px}aside ol{padding-left:20px;margin:8px 0;color:#c4d2e1}aside li{margin:5px 0;overflow-wrap:anywhere}.muted{color:var(--muted);line-height:1.55}.legend{display:grid;grid-template-columns:1fr 1fr;gap:8px}.key{display:flex;align-items:center;gap:7px;color:#b8c7d8}.dot{width:10px;height:10px;border-radius:50%}.stats{display:grid;grid-template-columns:1fr 1fr;gap:8px}.stat{background:#101925;border:1px solid #1d2a3b;border-radius:8px;padding:10px}.stat b{display:block;font-size:16px;color:white}.stat span{font-size:11px;color:var(--muted)}details{margin:9px 0;color:#b9c7d6}summary{cursor:pointer}hr{border:0;border-top:1px solid var(--line);margin:20px 0}
</style>
</head>
<body>
<header><div class="brand">Code<span>Map</span></div><input id="search" placeholder="Search files or modules…"><button id="fit">Fit</button><button id="edges">Show all edges</button><div class="summary">${result.files.length} files · ${result.edges.length} verified edges</div></header>
<main><section class="stage"><svg id="map" aria-label="Radial code dependency graph"><defs><marker id="arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7Z" fill="#22d3ee"/></marker></defs><g id="scene"><g id="sectors"></g><g id="edgeLayer"></g><g id="nodeLayer"></g></g></svg><div class="hint">Scroll to zoom · drag to pan · select a node to trace dependencies</div></section>
<aside><div id="detail"><h2>Radial architecture</h2><p class="muted">Each translucent sector is a module. Files orbit in deterministic rings; color shows source language. Select a file to isolate its incoming and outgoing dependencies.</p></div><hr><div class="legend"><div class="key"><i class="dot" style="background:#5eead4"></i>TypeScript</div><div class="key"><i class="dot" style="background:#facc15"></i>JavaScript</div><div class="key"><i class="dot" style="background:#60a5fa"></i>Python</div><div class="key"><i class="dot" style="background:#22d3ee"></i>Active edge</div></div><h3>Coverage</h3><div class="stats"><div class="stat"><b>${files.parsed}</b><span>parsed</span></div><div class="stat"><b>${result.edges.length}</b><span>verified edges</span></div><div class="stat"><b>${files.skipped}</b><span>skipped</span></div><div class="stat"><b>${imports.total.unresolved}</b><span>unresolved</span></div></div><details><summary>Unresolved imports</summary><ol id="unresolved"></ol></details><details><summary>Skipped files</summary><ol id="skipped"></ol></details></aside></main>
<script id="graphData" type="application/json">${data}</script>
<script>
const graph=JSON.parse(document.getElementById('graphData').textContent);
const svg=document.getElementById('map'),scene=document.getElementById('scene'),sectors=document.getElementById('sectors'),edgeLayer=document.getElementById('edgeLayer'),nodeLayer=document.getElementById('nodeLayer'),detail=document.getElementById('detail');
const NS='http://www.w3.org/2000/svg',TAU=Math.PI*2,colors={typescript:'#5eead4',javascript:'#facc15',python:'#60a5fa'};
const make=(name,attrs={})=>{const element=document.createElementNS(NS,name);Object.entries(attrs).forEach(([key,value])=>element.setAttribute(key,String(value)));return element};
const groups=[...new Map(graph.files.map(file=>[file.module,[]])).entries()];graph.files.forEach(file=>groups.find(group=>group[0]===file.module)[1].push(file));groups.sort((a,b)=>b[1].length-a[1].length||a[0].localeCompare(b[0]));
const weight=groups.reduce((sum,group)=>sum+Math.max(group[1].length,2),0),positions=new Map();let cursor=-Math.PI/2;
function polar(radius,angle){return{x:Math.cos(angle)*radius,y:Math.sin(angle)*radius}}
function sectorPath(inner,outer,start,end){const a=polar(inner,start),b=polar(outer,start),c=polar(outer,end),d=polar(inner,end),large=end-start>Math.PI?1:0;return 'M '+a.x+' '+a.y+' L '+b.x+' '+b.y+' A '+outer+' '+outer+' 0 '+large+' 1 '+c.x+' '+c.y+' L '+d.x+' '+d.y+' A '+inner+' '+inner+' 0 '+large+' 0 '+a.x+' '+a.y+' Z'}
groups.forEach(([module,items],moduleIndex)=>{const span=TAU*Math.max(items.length,2)/weight,start=cursor+.006,end=cursor+span-.006,rows=Math.max(1,Math.ceil(Math.sqrt(items.length/Math.max(span/TAU*8,.18)))),columns=Math.ceil(items.length/rows),inner=300,step=29,outer=inner+(rows-1)*step+34,hue=(moduleIndex*47)%360;sectors.append(make('path',{d:sectorPath(inner-22,outer,start,end),class:'module-sector',fill:'hsl('+hue+' 52% 42% / .09)',stroke:'hsl('+hue+' 58% 58% / .3)'}));const labelPoint=polar(inner-42,(start+end)/2),label=make('text',{x:labelPoint.x,y:labelPoint.y,class:'module-label'});label.textContent=module;sectors.append(label);items.sort((a,b)=>a.path.localeCompare(b.path)).forEach((file,index)=>{const row=index%rows,column=Math.floor(index/rows),angle=columns===1?(start+end)/2:start+(end-start)*(column+.5)/columns,radius=inner+row*step;positions.set(file.path,polar(radius,angle))});cursor+=span});
graph.edges.forEach((edge,index)=>{const source=positions.get(edge.source),target=positions.get(edge.target);if(!source||!target)return;const path=make('path',{d:'M '+source.x+' '+source.y+' Q 0 0 '+target.x+' '+target.y,class:'edge','data-index':index,'data-source':edge.source,'data-target':edge.target});edgeLayer.append(path)});
graph.files.forEach(file=>{const point=positions.get(file.path),group=make('g',{class:'node',transform:'translate('+point.x+' '+point.y+')','data-path':file.path,'data-module':file.module});const circle=make('circle',{r:5.5,fill:colors[file.language]});const title=make('title');title.textContent=file.path+' · '+file.language;circle.append(title);const label=make('text',{x:10,y:4});label.textContent=file.path.split('/').pop();group.append(circle,label);group.addEventListener('click',event=>{event.stopPropagation();select(file)});nodeLayer.append(group)});
function escape(value){return value.replace(/[&<>\"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[char]))}
function list(items){return items.length?'<ol>'+items.map(item=>'<li>'+escape(item)+'</li>').join('')+'</ol>':'<p class="muted">None</p>'}
function select(file){const outgoing=graph.edges.filter(edge=>edge.source===file.path),incoming=graph.edges.filter(edge=>edge.target===file.path),related=new Set([file.path,...outgoing.map(edge=>edge.target),...incoming.map(edge=>edge.source)]);document.querySelectorAll('.node').forEach(node=>{node.classList.toggle('selected',node.dataset.path===file.path);node.classList.toggle('related',related.has(node.dataset.path)&&node.dataset.path!==file.path);node.classList.toggle('dim',!related.has(node.dataset.path))});document.querySelectorAll('.edge').forEach(edge=>{const active=edge.dataset.source===file.path||edge.dataset.target===file.path;edge.classList.toggle('active',active);if(active)edge.setAttribute('marker-end','url(#arrow)');else edge.removeAttribute('marker-end')});detail.innerHTML='<h2>'+escape(file.path)+'</h2><p class="muted">'+file.language+' · '+file.lines+' lines · module '+escape(file.module)+'</p><h3>Dependencies</h3>'+list(outgoing.map(edge=>edge.target))+'<h3>Dependents</h3>'+list(incoming.map(edge=>edge.source))}
svg.addEventListener('click',()=>{document.querySelectorAll('.node').forEach(node=>node.classList.remove('selected','related','dim'));document.querySelectorAll('.edge').forEach(edge=>{edge.classList.remove('active');edge.removeAttribute('marker-end')})});
document.getElementById('search').addEventListener('input',event=>{const query=event.target.value.toLowerCase();document.querySelectorAll('.node').forEach(node=>node.classList.toggle('match',Boolean(query)&&(node.dataset.path.toLowerCase().includes(query)||node.dataset.module.toLowerCase().includes(query))))});
document.getElementById('edges').addEventListener('click',event=>{const active=scene.classList.toggle('show-all');event.target.classList.toggle('active',active);event.target.textContent=active?'Hide all edges':'Show all edges'});
graph.coverage.imports.unresolved.forEach(item=>{const li=document.createElement('li');li.textContent=item.from+':'+item.line+' → '+item.specifier;document.getElementById('unresolved').append(li)});graph.coverage.files.skippedFiles.forEach(item=>{const li=document.createElement('li');li.textContent=item.path+' — '+item.reason;document.getElementById('skipped').append(li)});
let zoom=1,offsetX=0,offsetY=0,drag=null;function apply(){scene.setAttribute('transform','translate('+offsetX+' '+offsetY+') scale('+zoom+')')}function fit(){const box=scene.getBBox(),viewport=svg.getBoundingClientRect();zoom=Math.max(.1,Math.min(1.5,Math.min((viewport.width-70)/Math.max(box.width,1),(viewport.height-70)/Math.max(box.height,1))));offsetX=viewport.width/2-(box.x+box.width/2)*zoom;offsetY=viewport.height/2-(box.y+box.height/2)*zoom;apply()}document.getElementById('fit').addEventListener('click',fit);svg.addEventListener('wheel',event=>{event.preventDefault();const old=zoom;zoom=Math.max(.08,Math.min(4,zoom*(event.deltaY<0?1.12:.89)));const rect=svg.getBoundingClientRect(),px=event.clientX-rect.left,py=event.clientY-rect.top;offsetX=px-(px-offsetX)*zoom/old;offsetY=py-(py-offsetY)*zoom/old;apply()},{passive:false});svg.addEventListener('pointerdown',event=>{drag={x:event.clientX-offsetX,y:event.clientY-offsetY};svg.setPointerCapture(event.pointerId);svg.classList.add('dragging')});svg.addEventListener('pointermove',event=>{if(!drag)return;offsetX=event.clientX-drag.x;offsetY=event.clientY-drag.y;apply()});svg.addEventListener('pointerup',()=>{drag=null;svg.classList.remove('dragging')});requestAnimationFrame(fit);
</script>
</body></html>`;
}
